### ISSUE TITLE
[BUG] ARCitect issue with network drive on windows

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#114]
I've run into an issue working on a network drive. 
Possibly related to #107. 

1. Fresh ARC in desktop folder
- ARCitect logged in: user name and email received from datahub
- ARCitect not logged in: user name from global gitconfig
2. Fresh ARC on network folder
- logged in / logged out: no user name or email

---
- OS: Windows 10
- ARCitect v0.0.24
- Fileshare: NetApp Grid

**Comment by Brilator** [comment]
Tried digging into this. 
- When running any git command (git status) in the ARC on network drive, I get an error "detected dubios ownership"
- This comes from the safeDirectory feature since git 2.36 or so https://git-scm.com/docs/git-config/#Documentation/git-config.txt-safedirectory. 
- when adding all directories as safe to the git config (`git config --global --add safe.directory *`). The ARC behaves like under 1, showing the name and email when logged in. This might however be a safety risk and it's actually not too bad to prevent working in other people's ARC's (by accident) on a shared folder. 
- Tried but failed to make this a bit stricter by adding the network drive only `git config --global --add safe.directory %(prefix)///servername/share`
- Adding a wildcard also did not do the job, I had to specifically provide the full path to the ARC `git config --global --add safe.directory %(prefix)///servername/share/path/to/ARC/repoB` to get this to work.

**Comment by Brilator** [comment]
The use-case (i.e. why even work on a network drive rather than arc syncing from individual machines): 
- all measuring devices producing large datasets are connected to that file share
- the file share is backed up regularly 
- lab members running the machines ideally move the data directly into the ARC on the file share and one or the other ARC-expert syncs it from there to the hub

**Comment by Brilator** [comment]
Two more errors with an ARC on the same drive: 

```
...
git status -z -u
fatal: couldn't read .git/packed-refs: Permission denied
git status -z -u
warning: unable to access '.git/config': Permission denied
```

So there's an issue with ARCitect being unable to read from the git inside that ARC. 
This happened only during the first two pushs of a fresh ARC and not anymore afterwards. The ARC was still uploaded just fine during each push.  
Cannot reproduce - new ARC, same drive, works just fine..

**Comment by GuichardM** [comment]
Hello,
I think this closed issue is actually related to my current issue. Here is the summary of it:

1. I have created an ARC on my Windows laptop, using an ARCitect release older than the 0.0.31
2. In order to get that ARC on an external hard drive connected on my Windows laptop, I used ARCitect(0.0.31)>Download ARC, and chose a custom path where to save the ARC in this hard drive
3. I have added some files in the ARC, through the hard drive (in that case in the protocol folder of an assay)
4. In ARCitect(0.0.31)>Commit, there is the message "No changes to commit"

I guess that this is because at the step 2 described above, this message poped up:
`git config --global --add safe.directory [path in the hard drive]/[ARC name]
git remote add origin https://git.nfdi4plants.org/marjorie.guichard/[ARC name].git
fatal: detected dubious ownership in repository at '[path in the hard drive]/[ARC name]'
'[path in the hard drive]/[ARC name]' is on a file system that doesnot record ownership
To add an exception for this directory, call:
git config --global --add safe.directory [path in the hard drive]/[ARC name]
Complete
`

So here are my questions:
Q1. Is my guess correct?
Q2. If Q1 true, how to fix this issue? (PS: with an answer understandable by someone not used to the usage of a git, or ARCcommander, please ;) )

Thank you for your help
