### ISSUE TITLE
[BUG] open button disabled after downloading ARC

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/ARCitect#165]
Windows 11, ARCitect 0.0.31

After downloading an existing ARC, the OPEN button in the dialog is always disabled. 
You could only close the dialog and open the ARC from the folder.

It would be easier if the open button worked and the ARC opened directly in ARCitect.
I'm not sure if the function doesn't exist at the moment or if it is a bug. 
![Screenshot 2024-03-14 083054](https://github.com/nfdi4plants/ARCitect/assets/127506066/fd5b3fd0-d793-4b89-810c-ac017d3b7e35)

**Comment by Brilator** [comment]
The open button works on my end. 
But you're also running into an error `fatal: credential-cache unavailable; no unix socket support`

**Comment by SabrinaZander** [comment]
I tried several other ARCs and I always run into this error: fatal: credential-cache unavailable; no unix socket support 
Any idea how to solve the error?

**Comment by Brilator** [comment]
The issue was solved by removing "credential.helper=cache" from user gitconfig by hand or via `git config --global --unset credential.helper`. Alternatively, it's solved by overwriting the setting with "store" instead of "cache" via `git config --global credential.helper store`.

Since `git config --global --unset credential.helper` could interfere / annoy when using ARCitect, I'd suggest to solve this via `git config --global credential.helper store` to overwrite the cache.
