### ISSUE TITLE
[Feature Request] Add XLSX git diff

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCitect#198]
The user should be able to preview and then choose:
- keep remote
- keep local
- keep automatic git merge

**Comment by HLWeil** [comment]
Little BUMP After a user request from our partners in FAIRagro:

Could we generalize this issue to a general diff?

In one case, they 
- created an ARC on the DataHub (only a README) 
- initialzed an ARC locally
- set the the URL of the one in the DataHUB as the remote for the local one
- tried to sync

Now, this did not work, as there were different histories online and offline. But in this case, an automatic Rebase could have solved the problem for the user.

**Comment by JonasLukasczyk** [comment]
This is work in progress, but since 5067c0430dc6263c101f520ba8e8c1b9107ac9e3 it is possible to attempt an xlsx merge when a merge conflict is detected. For now this works as follows:
1. When performing a pull and git detects a merge conflict then the ok button in the dialog changes to a "merge" button:
![image](https://github.com/user-attachments/assets/30e2ebba-fdc7-4e37-b111-28cb29f2a245)
2. When the user clicks on cancel then the repo reverts to the state before the pull request.
3. When the user clicks on the merge button then ARCitect performs the following steps
4. First ARCitect finds the latest commit both branches agree on which is called the ancestor
5. Then for each conflicted XLSX file ARCitect will download the XLSX file version of the ancestor, the local repo, and the remote repo. NOTE: Currently conflicts of non-xlsx files can not be resolved within ARCitect.
6. Then ARCitect transforms all the XLSX files into JSON files using `fsspreadsheet`
7. Next it uses the `git merge-file -p local_json ancestor_json remote_json` command to merge the files as if they were source code (how reliable this is needs to be seen).
8. If both the local and remote version changed the same cells, then the user has to decide which changes to keep.
9. The resulting merged JSON files are then transformed back to XLSX files and added in a new commit.

This definitely needs to be more tested.

**Comment by JonasLukasczyk** [comment]
This feature was added in 20198b6d0fc2ce6e4fb60b773577fa4120cef4c8

**Comment by Freymaurer** [comment]
@JonasLukasczyk Does this feature allow previewing local/remote/merge? can you post some images?
