### ISSUE TITLE
[BUG] renaming study / assay conflicts with commit reset

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCitect#205]
1. rename e.g. study via context menu
2. go to commit panel (see changes= removed files old-studyName, added files new-studyName)
3. Click "reset" (i.e. `git reset --hard`) 
4. Bug: added files new-studyName still present

**Comment by Brilator** [comment]
tested with https://github.com/nfdi4plants/ARCitect/commit/2b23c9258474a3d868848ae4a1f33e47afbf4084

**Comment by JonasLukasczyk** [comment]
This is expected behavior. Git reset does only restore **all tracked files** form a specific commit to the state of that commit. Other untracked files (for example those generated by copies) are not deleted by git. We could offer the following feature: a one button solution that deletes the entire ARC and performs a fresh clone. Then the ARC is completely reset to the state of the remote repo. **HOWEVER:** Any local commits not pushed to the remote will be lost plus all untracked files. So I do not know if this does more harm than good.

**Comment by JonasLukasczyk** [comment]
@Brilator I suggest the following feature: Of users click on the Reset button they will be presented with a dialog in  which they can choose from the following options:
1. Soft Reset: all files tracked by git will be reset to the last commited version, changes to those files are lost
2. Hard Reset: the content of the ARC is deleted including files not tracked by git, and then the files of the last commit are restored.

Should I add this?

should we add a button that resets the entire ARC to the state of the last commit (deleting all untracked files?). So the ARC will only include the files from git. If users added temporary files

**Comment by Brilator** [comment]
Sounds good to me

**Comment by Brilator** [comment]
For `hard reset` add a clear warning about possible data loss / making sure to have a copy.

**Comment by JonasLukasczyk** [comment]
Feature added in dfb05aaa2ba0f4cd96e0525e0df2a87631612664
