### ISSUE TITLE
[BUG] pull not possible before commit, creating conflicts

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/ARCitect#254]
**OS and framework information (please complete the following information):**
 - OS: Ubuntu 22.04
 - ARCitect v0.0.41

**Describe the bug**
I was working on the same ARC together with a colleague. 
- we both pulled it to our individual machines at the same time
- we both added some files and did some changes
- I committed and pushed my changes first
- now, my colleagues local ARC is out of sync so he would have to pull it again, but he also has local changes already (not committed yet)
- he can't pull the ARC since the ARCitect says "commit something first before pulling"
- I advised against committing since this would introduce a conflict error when he would try to push then

</br>

**Solutions**
- Solution: allow users to pull an ARC without any previous commit to allow multiple people working on an ARC at the same time
- I'm not sure why this is not possible in the first place, is there a reason for linking pulls and commits?
- temporary fix: I told my colleague to do a manual pull using the Ubuntu terminal and then commit and push, which worked fine

**Comment by JonasLukasczyk** [comment]
Hi, this is a safety precaution to prevent merge conflicts since merging divergent xlsx files is tricky and currently in development. Sometimes, like in this case, one can perform a pull without introducing a merge conflict if both did not edit the same xlsx files, but that was just a lucky coincidence (or maybe you did and now either you or your colleague lost work since files were overriden). In the near future it will be possible to merge xlsx file though. I will keep this issue open until we release this feature.

**Comment by JonasLukasczyk** [comment]
This is partially addressed with the new merge feature. Btw., in the described scenario even without your colleague performing a commit this could introduce a merge conflict. This always happens when local files are modified but during the pull they can not simply be forwarded (updated).
