### ISSUE TITLE
[BUG] after deleting assays they are still visible in the assay subtree 

### ISSUE THREAD

**Issue by langeipk** [nfdi4plants/ARCitect#313]
**OS and framework information (please complete the following information):**
 - OS: [e.g. LINUX]

**Describe the bug**
when droping a assay they are still visible. When shutdown, start and reload the investigation they are gone. This is true for version 0.0.50. In version 0.0.51 the deletion does not work at all

**Comment by JonasLukasczyk** [comment]
Thank you for raising this issue. I investigated the problem and it looks to me like `ARCtrl` renamed the `RemoveAssay` and `RemoveStudy` functions. There seems to be something weird going on because during testing these functions exist, but on release they are missing, instead an ARC only has the functions `RemoveAssayAsync` and `RemoveStudyAsync`. Can you have a look @HLWeil (this seems critical)

**Comment by JonasLukasczyk** [comment]
Downgrading `ARCtrl` to version 2.0.1 solves the issue.

**Comment by HLWeil** [comment]
Yes this is my fault for renaming existing functions between the releases:

`RemoveAssay` is now called `GetAssayRemoveContracts`.

**Comment by HLWeil** [comment]
`RenameAssayAsync` and such now also fulfill the Contracts, given `node` is installed.

**Comment by JonasLukasczyk** [comment]
Fixed in v0.0.52
