### ISSUE TITLE
[BUG] Missing Module 'electron-context-menu'

### ISSUE THREAD

**Issue by bfrommer** [nfdi4plants/ARCitect#51]
**OS and framework information:**
 - OS: Windows 11

**Describe the bug**
ARCitect Version 0.0.9 gives this error:

![Screenshot (21)](https://github.com/nfdi4plants/ARCitect/assets/91194167/3af90bc5-de05-4777-a015-95fc988f3cfb)

**Comment by Brilator** [comment]
same on macOS (using the .dmg)

**Comment by eik-dahms** [comment]
Had the same issue - install electron context menu handish.

`npm install electron-context-menu`

The issue seems to be in the package.json file. (line 30 in linux version)

`"electron-context-menu": "^3.6.1",`

I think the carrot is there by accident so I guess that is why it can not find it while installation.

**Comment by Brilator** [comment]
This won't work for the compiled executables

**Comment by JonasLukasczyk** [comment]
Fixed with v0.0.10
