### ISSUE TITLE
[Feature Request] sort folders according to workflows

### ISSUE THREAD

**Issue by tim-sch-gif** [nfdi4plants/ARCitect#57]
**Is your feature request related to a problem? Please describe.**
I do not like that the sorting of the folders inside the ARCitect is alpha-numeric because you cannot simply work your way downwards. The way it is ordered now does not align with the workflow of studies, assays, workflows, and finally runs.

**Describe the solution you'd like**
I would like the option to reorder the folders to follow the workflow.

**Comment by Brilator** [comment]
Hi Tim, thanks for the suggestion. I frankly renamed your issue (since you kept the "placeholder"). 

This is an interesting idea. However, I'm not sure it works with all scenarios of how people work with the ARC. 
Plus, the way the ARC is currently presented in ARCitect should exactly align with how your Windows Explorer / macOS Finder as well as the DataHUB display it.

**Comment by Brilator** [comment]
An alternative to achieve this, if I understand your point, is to use very rigid identifiers for your studies and assays (e.g. "stud-001", "stud-002", "assay-001_nameOfAssay")
